apiVersion: v1
kind: Pod
metadata:
  name: file-pod
spec:
  containers:
  - name: container
    image: nginx
    env:
    - name: cfile
      valueFrom:
        configMapKeyRef:
          name: fcm
          key: cfile.txt
    - name: sfile
      valueFrom:
        secretKeyRef:
          name: fsc
          key: sfile.txt
