apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: role-rb
subjects:
- kind: ServiceAccount
  name: role-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io
